<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <Description>The MonoGame Content Builder (MGCB) command line tool is used for optimizing content for runtime use.</Description>
    <BaseOutputPath>..\..\Artifacts\MonoGame.Content.Builder</BaseOutputPath>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>mgcb</ToolCommandName>
    <PackageId>dotnet-mgcb</PackageId>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <AssemblyName>mgcb</AssemblyName>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MonoGame.Framework\MonoGame.Framework.DesktopGL.csproj">
      <IncludeAssets>compile</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
    <ProjectReference Include="..\..\MonoGame.Framework.Content.Pipeline\MonoGame.Framework.Content.Pipeline.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\Artifacts\native\mgfx-spvc\windows\x64\$(Configuration)\mgfx-spvc.exe" Condition="Exists('..\..\Artifacts\native\mgfx-spvc\windows\x64\$(Configuration)\mgfx-spvc.exe')" Visible="false" Link="runtimes\win-x64\native\mgfx-spvc.exe" PackagePath="tools\net8.0\any\runtimes\win-x64\native" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Artifacts\native\mgfx-spvc\windows\arm64\$(Configuration)\mgfx-spvc.exe" Condition="Exists('..\..\Artifacts\native\mgfx-spvc\windows\arm64\$(Configuration)\mgfx-spvc.exe')" Visible="false" Link="runtimes\win-arm64\native\mgfx-spvc.exe" PackagePath="tools\net8.0\any\runtimes\win-arm64\native" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Artifacts\native\mgfx-spvc\linux\x64\$(Configuration)\mgfx-spvc" Condition="Exists('..\..\Artifacts\native\mgfx-spvc\linux\x64\$(Configuration)\mgfx-spvc')" Visible="false" Link="runtimes\linux-x64\native\mgfx-spvc" PackagePath="tools\net8.0\any\runtimes\linux-x64\native" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Artifacts\native\mgfx-spvc\linux\arm64\$(Configuration)\mgfx-spvc" Condition="Exists('..\..\Artifacts\native\mgfx-spvc\linux\arm64\$(Configuration)\mgfx-spvc')" Visible="false" Link="runtimes\linux-arm64\native\mgfx-spvc" PackagePath="tools\net8.0\any\runtimes\linux-arm64\native" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Artifacts\native\mgfx-spvc\macosx\$(Configuration)\mgfx-spvc" Condition="Exists('..\..\Artifacts\native\mgfx-spvc\macosx\$(Configuration)\mgfx-spvc')" Visible="false" Link="runtimes\osx-x64\native\mgfx-spvc" PackagePath="tools\net8.0\any\runtimes\osx-x64\native" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Artifacts\native\mgfx-spvc\macosx\$(Configuration)\mgfx-spvc" Condition="Exists('..\..\Artifacts\native\mgfx-spvc\macosx\$(Configuration)\mgfx-spvc')" Visible="false" Link="runtimes\osx-arm64\native\mgfx-spvc" PackagePath="tools\net8.0\any\runtimes\osx-arm64\native" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
