<Project>
  <PropertyGroup>
    <MonoGamePlatform>AndroidVK</MonoGamePlatform>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'android'">
    <AndroidManifestOverlay Include="$(MSBuildThisFileDirectory)MonoGame.Framework.Android.Vulkan.AndroidManifest.xml" />
    <AndroidNativeLibrary Include="$(MSBuildThisFileDirectory)..\runtimes\android-arm64\native\libmgruntime.so">
      <Abi>arm64-v8a</Abi>
      <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    </AndroidNativeLibrary>
  </ItemGroup>
</Project>
