<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>29</SupportedOSPlatformVersion>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    <AndroidManifest>Platform\Android\AndroidManifest.Vulkan.xml</AndroidManifest>
    <DefineConstants>ANDROID;VULKAN;NATIVE_GRAPHICS;STBSHARP_INTERNAL</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>The MonoGame runtime for Android using the Native Vulkan backend.</Description>
    <PackageTags>monogame;.net core;android;vulkan;native</PackageTags>
    <PackageId>MonoGame.Framework.Android.Vulkan</PackageId>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <IsAotCompatible>true</IsAotCompatible>
    <PackageReadmeFile>README-packages.md</PackageReadmeFile>
  </PropertyGroup>

  <Import Project="MonoGame.Framework.Native.Graphics.targets" />

  <ItemGroup>
    <None Include="..\README-packages.md" Pack="true" PackagePath="\"/>
    <None Include="MonoGame.Framework.Android.Vulkan.targets" Pack="true" PackagePath="buildTransitive" />
    <None Include="..\Artifacts\native\mgruntime\androidvk\android-arm64\$(Configuration)\libmgruntime.so"
          Pack="true"
          PackagePath="runtimes/android-arm64/native/libmgruntime.so" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="bin\**\*" />
    <Compile Remove="obj\**\*" />
    <Compile Remove="Platform\**\*" />
    <Compile Remove="Properties\**\*" />
    <Compile Remove="Utilities\System.Numerics.Vectors\**\*" />
    <Compile Remove="Devices\**\*" />
    <Compile Remove="GraphicsDeviceManager.cs" />
    <Compile Remove="Input\Keyboard.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Platform\**\*" />
    <None Remove="Utilities\System.Numerics.Vectors\**\*" />
    <None Include="Platform\Android\AndroidManifest.Vulkan.xml"
          Pack="true"
          PackagePath="buildTransitive/MonoGame.Framework.Android.Vulkan.AndroidManifest.xml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="@(MonoGameNativeGraphicsSource)" />
    <Compile Include="Platform\Android\AndroidCompatibility.cs" />
    <Compile Include="Platform\Android\AndroidGameActivity.cs" />
    <Compile Include="Platform\Android\AndroidGamePlatform.cs" />
    <Compile Include="Platform\Android\AndroidGameWindow.cs" />
    <Compile Include="Platform\Android\Devices\Sensors\Accelerometer.cs" />
    <Compile Include="Platform\Android\Devices\Sensors\Compass.cs" />
    <Compile Include="Platform\Android\Input\Keyboard.cs" />
    <Compile Include="Platform\Android\Input\Touch\AndroidTouchEventManager.cs" />
    <Compile Include="Platform\Android\IResumeManager.cs" />
    <Compile Include="Platform\Android\MonoGameAndroidGameView.cs" />
    <Compile Include="Platform\Android\MonoGameAndroidVulkanGameView.cs" />
    <Compile Include="Platform\Android\OrientationListener.cs" />
    <Compile Include="Platform\Android\ResumeManager.cs" />
    <Compile Include="Platform\Android\ScreenReceiver.cs" />
    <Compile Include="Platform\Audio\Xact\WaveBank.Default.cs" />
    <Compile Include="Platform\GamePlatform.Mobile.cs" />
    <Compile Include="Platform\Graphics\IGraphicsContext.OpenGL.cs" />
    <Compile Include="Platform\Graphics\IWindowInfo.OpenGL.cs" />
    <Compile Include="Platform\Graphics\OpenGL.Android.cs" />
    <Compile Include="Platform\Graphics\OpenGL.Common.cs" />
    <Compile Include="Platform\Graphics\OpenGL.cs" />
    <Compile Include="Platform\GraphicsDeviceManager.Legacy.cs" />
    <Compile Include="Platform\Input\GamePad.Android.cs" />
    <Compile Include="Platform\Input\Joystick.Default.cs" />
    <Compile Include="Platform\Input\KeyboardInput.Android.cs" />
    <Compile Include="Platform\Input\MessageBox.Android.cs" />
    <Compile Include="Platform\Input\Mouse.Default.cs" />
    <Compile Include="Platform\Input\MouseCursor.Default.cs" />
    <Compile Include="Platform\Media\MediaPlayer.Default.cs" />
    <Compile Include="Platform\PrimaryThreadLoader.cs" />
    <Compile Include="Platform\Threading.cs" />
    <Compile Include="Platform\TitleContainer.Android.cs" />
    <Compile Include="Platform\Utilities\FuncLoader.Android.cs" />
    <Compile Include="Platform\Utilities\InteropHelpers.cs" />
    <Compile Include="Platform\Utilities\ReflectionHelpers.Default.cs" />

    <Compile Include="..\ThirdParty\StbImageSharp\src\**\*.cs" LinkBase="Utilities\StbImageSharp" />
    <Compile Include="..\ThirdParty\StbImageWriteSharp\src\**\*.cs" LinkBase="Utilities\StbImageWriteSharp" />
  </ItemGroup>

  <Import Project="Platform\OpenAL.targets" />
  <Import Project="MonoGame.Framework.Devices.Sensors.targets" />
</Project>
