<Project>

  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <MonoGamePlatform>VisionOSInputContract</MonoGamePlatform>
    <BaseIntermediateOutputPath>obj/</BaseIntermediateOutputPath>
    <BaseOutputPath>../../Artifacts/Tests/VisionOSInputContract/</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

</Project>
